### ISSUE TITLE
Check if there is a clean solution to prevent hashtag links inside of links

### ISSUE THREAD

**Issue by svbergerem** [svbergerem/markdown-it-hashtag#1]
The link text may have some markup so most inline rules also apply for those texts. We don't want hashtag markup inside of link texts because then we would have a link inside of a link.

To prevent that the current implementation goes through the token stream and replaces all hashtag tokens between `link_open` and `link_close` with `text` tokens. The code can be found here: https://github.com/svbergerem/markdown-it-hashtag/blob/develop/index.js#L115

One should check if there is a cleaner solution for that issue. It would be great if we could make sure that the hashtag rule isn't applied inside of links at all. (before even looking for hashtags)

**Comment by svbergerem** [comment]
@puzrin it would be great if you could help.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/linkify.js#L68

**Comment by puzrin** [comment]
Also pay attention to this 2 helpers https://github.com/markdown-it/markdown-it/blob/master/lib/common/utils.js#L238-L239 (those are exposed in each instance `md.utils`).

I think, it's good idea to check, that chars before/after found pattern are start/end of string, whitespace or punctuation. We have those helpers, because JS regexps do not support unicode, and `xregexp` package is too big for embedding.

**Comment by svbergerem** [comment]
@puzrin Thank you. The code in linkify.js helped a lot.

I didn't use the 2 helper functions because the main reason why I am writing this plugin is that I would like to use markdown-it for diaspora* and our patterns don't care about chars that come after the hashtag. Our rule for preceding chars is `\s|^` and I did not want to change our patterns while doing the first step.

On the other hand I wanted to make this plugin as configurable as possible. Because of that I let the user decide which chars are accepted before the matched pattern. I might in a future iteration also let the user define which chars are allowed after the matched pattern if someone needs that feature.
