### ISSUE TITLE
How to use if manually installed

### ISSUE THREAD

**Issue by Abrahamlet** [svbergerem/markdown-it-hashtag#3]
How do you configure and use this plugin if it's added to the webpage via script tag (manually installed)?

**Comment by svbergerem** [comment]
See the [README](https://github.com/svbergerem/markdown-it-hashtag#use):

> If you load the script directly into the page, without package system, module will add itself globally as `window.markdownitHashtag`.

Thus you could use the plugin like this:
```javascript
var md = window.markdownit();
md.use(window.markdownitHashtag, {
  // pattern for hashtags with normal string escape rules
  hashtagRegExp: '\\w+',
  // pattern for allowed preceding content
  preceding:     '^|\\s'
});
```
